#!/usr/bin/env bash

python scripts/publication_figures.py enso_comprehensive.eps false 1 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py nao_comprehensive.eps true 5 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp04_comprehensive.eps true 3 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp12_comprehensive.eps false 11 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp25_comprehensive.eps true 24 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp25_comprehensive_pacific.eps false 24 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp30_comprehensive.eps true 29 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp24_comprehensive.eps true 23 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

python scripts/publication_figures.py comp32_comprehensive.eps false 31 results/slp_all_var_b0_cosweights_varimax_detrended.bin results/slp_all_var_b0_cosweights_varimax.bin results/slp_all_var_b0_cosweights_varimax_detrended_55.bin results/slp_all_var_b0_cosweights_varimax_detrended_65.bin results/slp2x2_all_var_b0_cosweights_varimax_detrended.bin

# also slp_all_detrend: 4, 12, 25 (both centers), 30, 24, 32
